# training_utils.py ── utility helpers for JEPA training & checkpoint I/O
# ────────────────────────────────────────────────────────────────────────
# 1.  train_jepa(...)         : core loss loop for one role’s models
# 2.  load_role_models(role)  : lazy checkpoint loader / initializer
# 3.  run_sim_and_collect_rollouts(...) : convenience wrapper around sim.py
#
# NOTE:  This file never calls encode_current_belief itself; that work is done
#        inside sim.py while generating the rollout tuples.
# ────────────────────────────────────────────────────────────────────────

from __future__ import annotations

import os
import random
from typing import List, Tuple

import torch
import torch.nn as nn
import torch.optim as optim

from encoders import ActionEncoder, PlannerHead, WorldModelMLP

# --------------------------------------------------------------------- #
#  Global constants & checkpoint dir
# --------------------------------------------------------------------- #
CHECKPOINT_DIR = "checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# Device helper – keeps everything on same device for this file
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# --------------------------------------------------------------------- #
#  JEPA Training Loop
# --------------------------------------------------------------------- #
def train_jepa(
    rollout_data: List[Tuple[torch.Tensor, torch.Tensor, torch.Tensor, str]],
    world_model: WorldModelMLP,
    action_encoder: ActionEncoder,
    planner: PlannerHead,
    role_name: str = "agent",
    *,
    epochs: int = 5,
    batch_size: int = 16,
    learning_rate: float = 1e-3,
) -> None:
    """
    Update the three JEPA sub-modules (world_model, action_encoder, planner)
    using roll-outs generated by `sim.py`.

    Parameters
    ----------
    rollout_data : list[(z_t, a_t_idx, z_next, role)]
        The dataset used for regression to the next latent.
    world_model / action_encoder / planner : nn.Module
        Model components tied to the role we’re training.
    role_name : str
        Friendly label used for logging + checkpoint file naming.
    epochs, batch_size, learning_rate : hyper-parameters
    """

    # Ensure modules are on the same device
    world_model.to(DEVICE)
    action_encoder.to(DEVICE)
    planner.to(DEVICE)

    optimizer = optim.Adam(
        list(world_model.parameters())
        + list(action_encoder.parameters())
        + list(planner.parameters()),
        lr=learning_rate,
    )
    mse_loss = nn.MSELoss()

    world_model.train(), action_encoder.train(), planner.train()

    for ep in range(1, epochs + 1):
        random.shuffle(rollout_data)  # in-place shuffle

        # Chunk into mini-batches
        batches = [
            rollout_data[i : i + batch_size]
            for i in range(0, len(rollout_data), batch_size)
        ]

        epoch_loss = 0.0
        for batch in batches:
            # -- stack each component of the tuple -----------------------
            z_t, a_idx, z_next = zip(*[(r[0], r[1], r[2]) for r in batch])
            z_t_tensor = torch.stack(z_t).to(DEVICE)            # [B, latent]
            a_idx_tensor = torch.stack(a_idx).long().squeeze().to(DEVICE)
            z_next_tensor = torch.stack(z_next).to(DEVICE)

            # -- forward -----------------------------------------------
            a_embed = action_encoder(a_idx_tensor)               # [B, a_dim]
            z_pred = world_model(z_t_tensor, a_embed)            # [B, latent]

            loss = mse_loss(z_pred, z_next_tensor)

            # -- backward ----------------------------------------------
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

        avg = epoch_loss / max(1, len(batches))
        print(f"[{role_name}  Epoch {ep}/{epochs}]  MSE: {avg:.4f}")

    # ---------------------------------------------------------------- #
    #  Save checkpoint
    # ---------------------------------------------------------------- #
    save_path = os.path.join(CHECKPOINT_DIR, f"{role_name.lower()}_jepa.pt")
    torch.save(
        {
            "world_model": world_model.state_dict(),
            "action_encoder": action_encoder.state_dict(),
            "planner": planner.state_dict(),
        },
        save_path,
    )
    print(f"[SAVE] {role_name} models saved → {save_path}")


# --------------------------------------------------------------------- #
#  Model I/O helpers
# --------------------------------------------------------------------- #
def load_role_models(
    role: str,
) -> Tuple[WorldModelMLP, ActionEncoder, PlannerHead]:
    """
    Load checkpointed parameters for a role if present, else initialize
    fresh modules.

    Returns
    -------
    (world_model, action_encoder, planner)
    """
    wm = WorldModelMLP(latent_dim=32, action_dim=8)
    ae = ActionEncoder(num_actions=6, action_dim=8)
    planner = PlannerHead(latent_dim=32, num_agents=6)

    ckpt_path = os.path.join(CHECKPOINT_DIR, f"{role.lower()}_jepa.pt")
    if os.path.exists(ckpt_path):
        print(f"[LOAD] {role} checkpoint ← {ckpt_path}")
        state = torch.load(ckpt_path, map_location="cpu")
        wm.load_state_dict(state["world_model"])
        ae.load_state_dict(state["action_encoder"])
        planner.load_state_dict(state["planner"])
    else:
        print(f"[INIT] No checkpoint for {role}. Starting fresh.")

    return wm, ae, planner


# --------------------------------------------------------------------- #
#  Simulation wrapper
# --------------------------------------------------------------------- #
def run_sim_and_collect_rollouts(visual: bool = False):
    """
    Launch a game simulation (see sim.py) and return the rollout list.

    Parameters
    ----------
    visual : bool
        Whether to display the Pygame UI.

    Returns
    -------
    list
        The raw rollout tuples emitted by `simulate_game`.
    """
    # Local import to avoid circular dependency on startup
    from sim import simulate_game  # pylint: disable=import-error

    return simulate_game(visual=visual)
